### ISSUE TITLE
Feature Request: Add `onStart` callback

### ISSUE THREAD

**Issue by harunurhan** [josepot/react-redux-scroll#14]
Useful when you want to dispatch actions prior to scrolling.

For example I have too many tabs/accordions on the page and I have to open the right one before I scroll to an element.

(I could work on it, if you @josepot, are willing to review/merge/release)

**Comment by josepot** [comment]
Hi @harunurhan !

Thanks for the suggestion and sorry that it took me a couple of days to answer... I just saw this message.

Let me give it some thought, I will get back to you on this one before the end of the weekend.

**Comment by josepot** [comment]
Hi @harunurhan ,

I've been thinking about this and I'm sorry but I don't quite get it.

The way I see it is this: in redux apps actions are used as a way to describe what's happening... Sometimes those actions will be used by the root-reducer in order to generate a new state, sometimes those actions will be used by one of the middlewares to orchestrate some side-effect (e.g. redux-saga, redux-observable, react-redux-scroll, etc) and in some instances the same action will be used by both: the rootReducer and the middlewares... Right?

So, the idea of `react-redux-scroll` is to provide a middleware that handles a typical cross-cutting concern of an app: the orchestration of the scrolls... Anything that it is not that: belongs somewhere else.

Meaning that IMO the correct place where to dispatch a custom action "prior to scrolling" is somewhere else... If you are using `redux-saga` you would do that in a saga, if you are using `redux-observable` you would do it in an epic, or even in a thunk if you are using `redux-thunk`, etc.

> For example I have too many tabs/accordions on the page and I have to open the right one before I scroll to an element.

So, just open that "right one" and once it opens, dispatch an action that describes that the tab/accordion has been opened and then use that action in order to scroll to the element that you want to scroll.

I think that coupling the logic of opening the "right tab" into this middleware goes beyond the scope of this library and I don't think that's a good idea.

I'm not against the idea of optionally dispatching generic actions like `SCROLL_STARTED`, `SCROLL_FINISHED` and `SCROLL_CANCELED`. It would be a bit challenging, but it could make sense. Would that help your use-case?

Also, please forgive me if I didn't quite understand what you are suggesting. I'm very open to feedback and PRs are more than welcomed. I'm not trying to shut you down. So, if you think that there is something that I'm missing, I would really appreciate it if you could provide me with a minimal repo or gist that illustrates your problem.
