### ISSUE TITLE
unable to build the library Server Side

### ISSUE THREAD

**Issue by iamdey** [josepot/react-redux-scroll#6]
Due to accessing to `window` directly, it fails to import in a SSR build.

For now I've to use some tricks to use it only [in browser build](https://github.com/CaliOpen/Caliopen/pull/551/files#diff-b986287a9e53b733bf4ef1e01861ce96L44). 

It could be better to use `window` as a service declared at runtime instead, maybe.

PS: thank you to making this open-source.

**Comment by josepot** [comment]
Hi and thanks for reporting this issue!

I actually ran into a similar situation not to long ago and I did something pretty similar to what you are doing... I didn't think it was a big deal, because this library is meant to be used in the browser only... In a server-side build it should be completely disabled.

However, I agree that it would be pretty nice to have an easy way to completely disable this library for the SSR build, that's what #7 tries to accomplish. Could you please have a look at that PR and let me know if that works for you?

Thanks!

Josep
